defaults:
  - config_teleop

run_name: OmniH2O_TEACHER
num_envs: 8192

env:
  num_observations: 913
  num_privileged_obs: 990

motion:
  teleop_obs_version: v-teleop-extend-max-full
  teleop_selected_keypoints_names : [ 'pelvis',  'left_hip_yaw_link', 'left_hip_roll_link','left_hip_pitch_link', 'left_knee_link', 'left_ankle_link', 'right_hip_yaw_link', 'right_hip_roll_link', 'right_hip_pitch_link', 'right_knee_link', 'right_ankle_link', 'torso_link', 'left_shoulder_pitch_link', 'left_shoulder_roll_link', 'left_shoulder_yaw_link', 'left_elbow_link',  'right_shoulder_pitch_link', 'right_shoulder_roll_link', 'right_shoulder_yaw_link', 'right_elbow_link']

rewards:
  penalty_curriculum: True
  penalty_scale: 0.5




